### PR TITLE
Comp

### PR DESCRIPTION
**Pull request by AndKram**
Changes for BuildBattle (pending review by others)

### CODE REVIEW

**Comment by spMohanty** [comment]
@AndKram : Can you also fix this conflict ?

**Comment by spMohanty** [comment]
Okay merged. Thanks.

**Comment by AndKram** [comment]
Sorry, what conflict?

Andre

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by spMohanty** [comment]
@AndKram : Nevermind. It was a simple one, I resolved it.

**Comment by AndKram** [comment]
I mentioned the commit on Malmo gitter but we probably need a longer explanation to make it easier for people to get started.

Andre

**Pull request merged**
